package com.mydomain.temp;

// Generated 26-Mar-2009 11:47:41 by Hibernate Tools 3.2.2.GA

/**
 * BasketItemId generated by hbm2java
 */
public class BasketItemId implements java.io.Serializable {

	private Long itemsId;
	private Long basketId;

	public BasketItemId() {
	}

	public BasketItemId(Long itemsId, Long basketId) {
		this.itemsId = itemsId;
		this.basketId = basketId;
	}

	public Long getItemsId() {
		return this.itemsId;
	}

	public void setItemsId(Long itemsId) {
		this.itemsId = itemsId;
	}

	public Long getBasketId() {
		return this.basketId;
	}

	public void setBasketId(Long basketId) {
		this.basketId = basketId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BasketItemId))
			return false;
		BasketItemId castOther = (BasketItemId) other;

		return (this.getItemsId() == castOther.getItemsId()) && (this.getBasketId() == castOther.getBasketId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemsId();
		result = 37 * result + (int) this.getBasketId();
		return result;
	}

}
