package com.mydomain.temp;

// Generated 26-Mar-2009 11:47:41 by Hibernate Tools 3.2.2.GA

/**
 * BasketItem generated by hbm2java
 */
public class BasketItem implements java.io.Serializable {

	private BasketItemId id;

	public BasketItem() {
	}

	public BasketItem(BasketItemId id) {
		this.id = id;
	}

	public BasketItemId getId() {
		return this.id;
	}

	public void setId(BasketItemId id) {
		this.id = id;
	}

}
