package com.mydomain.temp;

// Generated 26-Mar-2009 11:47:41 by Hibernate Tools 3.2.2.GA

/**
 * Basket generated by hbm2java
 */
public class Basket implements java.io.Serializable {

	private Long id;
	private String userid;

	public Basket() {
	}

	public Basket(Long id) {
		this.id = id;
	}

	public Basket(Long id, String userid) {
		this.id = id;
		this.userid = userid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
