package com.mydomain.temp;

// Generated 26-Mar-2009 11:47:41 by Hibernate Tools 3.2.2.GA

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Long id;
	private String description;
	private String name;
	private Double price;

	public Item() {
	}

	public Item(Long id) {
		this.id = id;
	}

	public Item(Long id, String description, String name, Double price) {
		this.id = id;
		this.description = description;
		this.name = name;
		this.price = price;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
